### ISSUE TITLE
Caching strategy object

### ISSUE THREAD

**Issue by marcus7777** [KanoComputing/kano-api-client#3]
After trying out lots of different caching strategies and being frustrated by them.
Here is a way that will give us the flexibility we need. (and won't annoy me)

I'm thinking the caching strategy could be an object with this structure:

  * cache
    * path
      * event / true / false
        * seconds / true / false
  * sync
    * path
      * event / true / false
        * seconds / true / false

## "path"
a dot(.) separated list of alphanumeric characters and anything that starts with that it an empty string signifies default
## "event"
notWrittenToFor, notReadFromIn, login, logout, share, close, afterSuccessfulSync

example: 
```
{
  cache: {
    "user.email": false,
    "analytics": {
      afterSuccessfulSync: false,
      logout: false,
    },
    "shares": {
      notReadFromIn: 432000,
    },
  },
  sync:
    "analytics": {
      afterSuccessfulSync: 300, 
      logout: true,
    },
  },
}
```

in this example:
  Will not cache the user's email.
  The analytics will only be sent every 5 minutes unless the user is logging out
  When the analytics have been successfully sunk they will be deleted from the cache.
  If the share hasn't been read for five days it will be deleted from the cache.

Everything else will be cache indefinitely and sync immediately (on idle). 

p.s. In the future as well as cache and sync I'd like to add decrypt and encrypt

**Comment by russormes** [comment]
If I understand correctly, this is meta data describing the behaviour of the cache that lives alongside the data?

One thing I would like to suggest is that the TTL be assigned on an data item level. It can be related to frequency or volume of views. That way a 'share', for example, that is often viewed gets a longer cache live than one that is viewed once or twice. This can allow us to eventually fill the cache with the most relevant data and when every  we need to make room in a crowded cache, we clear out the data with the lowest ttl (here I mean forced removal of data, not expired data).

However, this may be more relevant to the middle tier where we will want to keep the cache filled to capacity, although it seems relevant to the client too as we have less memory allocated to caching on the client than the middle tier.

What do you think?

**Comment by marcus7777** [comment]
This is exactly what I was thinking too, this is the parameter that is passed in when substantiating the caching API.

Then under the hood:
when we are running out of space on the client I was thinking of using the event "notReadFromIn" to work out what is least relevant and make space for new data.

**Comment by marcus7777** [comment]
Keeping a table of when things were last red may be useful to be sent to the server to know what cache should be cleared. I'll get it working locally first and then we can see whether it will work with the middle layer on the server. Sounds good?

**Comment by russormes** [comment]
Ok, but that prioritises items that were recently read, some of which might not be frequently used items and may never be looked at again. Same idea, just a different metric. I'll think it through and present is an example.

**Comment by russormes** [comment]
In general though, this is a nice proposal for controlling the caching policy per application.

**Comment by marcus7777** [comment]
Thanks
How about using last accessed and accesses over last 'n' days
